repositories:
- data/src/main/resources/repo
- data/src/main/resources/databases
- data/src/main/resources/GenericFDC
roots:
- repo
- databases
preferences: preferences.xml
perspectives:
    - perspective:
        name: Default
        priority: 0
        projectSelector: true
        repository:
            - tab:
                title: Repo Title
                path: repo
            - tab:
                title: Databases
                path: databases
                databases: true
            - tab:
                title: Generic FDC
                path: GenericFDC
        viewparts:
            - rule:
                name: allow
                id: track.finder
            - rule:
                name: allow
                id: sequence.sites
        actions:
            - rule: 
                name: deny
                id: Apply antimony
            - rule:
                name: deny
                id: combine_tracks
        importers:
            name: test